export const reduxActionTypes = {
  SET_USER: "SET_USER",
  REMOVE_USER: "REMOVE_USER",
  SET_POSTS: "SET_POSTS",
  GET_MORE_POSTS: "GET_MORE_POSTS",
  HAS_MORE_POSTS: "HAS_MORE_POSTS",
  UPDATE_POST: "UPDATE_POST",
  CREATE_POST: "CREATE_POST",
  SET_TODOS: "SET_TODOS",
  GET_MORE_TODOS: "GET_MORE_TODOS",
  HAS_MORE_TODOS: "HAS_MORE_TODOS",
  UPDATE_TODO: "UPDATE_TODO",
};
